import { App } from 'vue'
import {
  ElContainer,
  ElHeader,
  ElFooter,
  ElAside,
  ElMain,
  ElIcon,
  ElButton,
  ElLink,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElCheckbox,
  ElCheckboxButton,
  ElCheckboxGroup,
  ElInput,
  ElInputNumber,
  ElSelect,
  ElOptionGroup,
  ElCascader,
  ElCascaderPanel,
  ElSwitch,
  ElSlider,
  ElUpload,
  ElRate,
  ElColorPicker,
  ElTransfer,
  ElForm,
  ElFormItem,
  ElTag,
  ElProgress,
  ElTree,
  ElBadge,
  ElAvatar,
  ElAlert,
  ElLoading,
  ElMenu,
  ElMenuItem,
  ElSubmenu,
  ElMenuItemGroup,
  ElTabs,
  ElTabPane,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPageHeader,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElSteps,
  ElStep,
  ElDialog,
  ElPopover,
  ElPopconfirm,
  ElCard,
  ElCarousel,
  ElCarouselItem,
  ElCollapse,
  ElCollapseItem,
  ElTimeline,
  ElTimelineItem,
  ElDivider,
  ElCalendar,
  ElImage,
  ElBacktop,
  ElScrollbar,
  ElSkeleton
} from 'element-plus'

export default function(app:App) {
  app.use(ElContainer)
    .use(ElHeader)
    .use(ElFooter)
    .use(ElAside)
    .use(ElMain)
    .use(ElIcon)
    .use(ElButton)
    .use(ElLink)
    .use(ElRadio)
    .use(ElRadioButton)
    .use(ElRadioGroup)
    .use(ElCheckbox)
    .use(ElCheckboxButton)
    .use(ElCheckboxGroup)
    .use(ElInput)
    .use(ElInputNumber)
    .use(ElSelect)
    .use(ElOptionGroup)
    .use(ElCascader)
    .use(ElCascaderPanel)
    .use(ElSwitch)
    .use(ElSlider)
    .use(ElUpload)
    .use(ElRate)
    .use(ElColorPicker)
    .use(ElTransfer)
    .use(ElForm)
    .use(ElFormItem)
    .use(ElTag)
    .use(ElProgress)
    .use(ElTree)
    .use(ElBadge)
    .use(ElAvatar)
    .use(ElAlert)
    .use(ElLoading)
    .use(ElMenu)
    .use(ElMenuItem)
    .use(ElSubmenu)
    .use(ElMenuItemGroup)
    .use(ElTabs)
    .use(ElTabPane)
    .use(ElBreadcrumb)
    .use(ElBreadcrumbItem)
    .use(ElPageHeader)
    .use(ElDropdown)
    .use(ElDropdownItem)
    .use(ElDropdownMenu)
    .use(ElSteps)
    .use(ElStep)
    .use(ElDialog)
    .use(ElPopover)
    .use(ElPopconfirm)
    .use(ElCard)
    .use(ElCarousel)
    .use(ElCarouselItem)
    .use(ElCollapse)
    .use(ElCollapseItem)
    .use(ElTimeline)
    .use(ElTimelineItem)
    .use(ElDivider)
    .use(ElCalendar)
    .use(ElImage)
    .use(ElBacktop)
    .use(ElScrollbar)
    .use(ElSkeleton)
}
